{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SalesLT Customer\",\"MeganTable1031\",\"AdminTableDemo\",\"testTableAdmin\",\"SalesLT CustomerAddress\",\"SalesLT SalesOrderHeader\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.1066.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBI_RemovedChildren",
        "value": "[{\"remoteItemId\":{\"foreignKeyRelationship\":{\"fromTableLocalLineageTag\":\"fcb83d7a-dee1-4fb4-9c53-f24db5e4aa79\",\"fromColumnLocalLineageTag\":\"e2c86490-11bc-4dc3-b49f-89c7accf1f1d\",\"toTableLocalLineageTag\":\"3bb2b7bb-6203-40e6-be60-99c9e465e484\",\"toColumnLocalLineageTag\":\"9577defa-b34d-4c0e-9c42-42f9dd618f64\"}},\"objectType\":\"Relationship\"}]"
      }
    ],
    "culture": "zh-CN",
    "cultures": [
      {
        "name": "zh-CN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "5c46d3ba-3837-4af7-b82d-a0309e81c091",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "CustomerID",
        "fromTable": "SalesLT CustomerAddress",
        "toColumn": "CustomerID",
        "toTable": "SalesLT Customer"
      },
      {
        "name": "b63d8bce-bf85-4598-af0c-f512c66f8804",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "crossFilteringBehavior": "bothDirections",
        "fromCardinality": "one",
        "fromColumn": "CustomerID",
        "fromTable": "SalesLT Customer",
        "toColumn": "CustomerID",
        "toTable": "SalesLT SalesOrderHeader"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "SalesLT Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9577defa-b34d-4c0e-9c42-42f9dd618f64",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "NameStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e7be88c2-96e8-43c0-a799-f16853edd646",
            "sourceColumn": "NameStyle",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f3b4adb-6ffe-4ee7-b70a-3959246f9735",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a85b6db-5a6e-4d63-9f30-b404c7389bc2",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3b76758-5481-4a60-b49f-b8470d468420",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dafac656-8b08-4fab-8da9-4ae70a3eed67",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcaf659d-51d6-411c-98cc-06bc686733d6",
            "sourceColumn": "Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdf0c4c3-a932-4ba6-bd75-9e302adc0763",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "SalesPerson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87ba49cd-2fed-4f71-8aff-ea36909c3ee2",
            "sourceColumn": "SalesPerson",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "778458ec-06a0-4ea9-8b80-ac55b4c3cf6c",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60d4971a-ca06-48ce-ba7b-586b9b4f817d",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3bb2b7bb-6203-40e6-be60-99c9e465e484",
        "partitions": [
          {
            "name": "SalesLT Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"azuresqlserver0517.database.windows.net\", \"sampleDB\"),",
                "    SalesLT_Customer = Source{[Schema=\"SalesLT\",Item=\"Customer\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(SalesLT_Customer, each ([CustomerID] = 1 or [CustomerID] = 2 or [CustomerID] = 3 or [CustomerID] = 4 or [CustomerID] = 5)),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"PasswordHash\", \"PasswordSalt\", \"rowguid\", \"ModifiedDate\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_14f117e9-8b5c-42bd-b059-7ae4b9a61034",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6f44f863-fc45-4d68-90cf-8eb58373a53f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "1b3db7c8-56db-44a2-93e3-41c6f021be38",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5c9f05e8-caf3-42d9-859c-a470dd0baf4c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d7191689-e9d0-4eba-acd2-faa1d154bb93",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e0e0d165-357e-487b-93d2-ec00e6ba9617",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "30f4f555-eda4-4c37-9d56-602853a338e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "47235b57-8445-44dd-a038-c8c6544f1d80",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "565df087-da06-455e-b223-d4e796082a10",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "2b41daee-a6a3-4c1f-8655-502c55c2758a",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "f1baf523-f13a-420c-837c-f90d88267f6b",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "516f5a75-8708-4c94-a699-a6faed9d7edd",
                "ordinal": 3
              }
            ],
            "lineageTag": "cfc06344-174d-4f3a-9328-f893ff71bfe8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e686ae32-7ddb-4b2b-a12d-0d158f4be259",
        "partitions": [
          {
            "name": "DateTableTemplate_14f117e9-8b5c-42bd-b059-7ae4b9a61034",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "AdminTableDemo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b87410fc-3be6-4a4d-86c7-ada02ca55ef9",
            "sourceColumn": "Key",
            "summarizeBy": "count"
          },
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "63327c8a-95ad-499d-ad7b-45ebe831aea5",
            "sourceColumn": "Value",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f85e23f8-34a1-4028-93bf-e5dd4822b0ae",
        "partitions": [
          {
            "name": "AdminTableDemo",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUSopL04sUYrViVYyAvLy88FMQ7BMajFQIhYA\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Key = _t, Value = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"Key\", Int64.Type}, {\"Value\", type text}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "MeganTable1031",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Column1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e1089f25-2bfb-4144-af88-9e909d61e473",
            "sourceColumn": "Column1",
            "summarizeBy": "sum"
          },
          {
            "name": "Column2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "942516d0-5693-47ee-a1a3-7de6c8995075",
            "sourceColumn": "Column2",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "aea1c446-ff7a-4044-8be8-1c52f3579f78",
        "partitions": [
          {
            "name": "MeganTable1031",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSUSpJLS4xVIrViVYygvKMwDxjKM8YzDOB8kyUYmMB\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t, Column2 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", Int64.Type}, {\"Column2\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "testTableAdmin",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "col",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e31cd0d7-be6e-437a-a702-37aa8f69b2c6",
            "sourceColumn": "col",
            "summarizeBy": "sum"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b3190a36-eb51-4cf3-bca9-994b64d46aaf",
            "sourceColumn": "name",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4592b641-6ed6-4ad3-beab-ae97ae6bce0a",
        "partitions": [
          {
            "name": "testTableAdmin",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlTSAeJYnWglIyDLSCk2FgA=\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [col = _t, name = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"col\", Int64.Type}, {\"name\", Int64.Type}})",
                "in",
                "    更改的类型"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesLT CustomerAddress",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e2c86490-11bc-4dc3-b49f-89c7accf1f1d",
            "sourceColumn": "CustomerID",
            "summarizeBy": "count"
          },
          {
            "name": "AddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "10cdca5b-39fb-4298-b4a8-0d9d035584ca",
            "sourceColumn": "AddressID",
            "summarizeBy": "count"
          },
          {
            "name": "AddressType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96387721-1c06-4100-91d6-9340d6b9d13d",
            "sourceColumn": "AddressType",
            "summarizeBy": "none"
          },
          {
            "name": "rowguid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c29ef66-ee72-4eaf-996b-d22372fb0109",
            "sourceColumn": "rowguid",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fcb83d7a-dee1-4fb4-9c53-f24db5e4aa79",
        "partitions": [
          {
            "name": "SalesLT CustomerAddress",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"azuresqlserver0517.database.windows.net\", \"sampleDB\"),",
                "    SalesLT_CustomerAddress = Source{[Schema=\"SalesLT\",Item=\"CustomerAddress\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(SalesLT_CustomerAddress,{\"ModifiedDate\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesLT SalesOrderHeader",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesOrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a97f5650-2bd1-4cb7-89a2-7f97dd6616d9",
            "sourceColumn": "SalesOrderID",
            "summarizeBy": "count"
          },
          {
            "name": "RevisionNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "827954ea-f799-4d05-976d-30e1a316eae3",
            "sourceColumn": "RevisionNumber",
            "summarizeBy": "sum"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53e2903c-3feb-4b1d-9447-74e6fdc71a81",
            "sourceColumn": "Status",
            "summarizeBy": "sum"
          },
          {
            "name": "OnlineOrderFlag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "36fbb8ca-b09c-4f88-b258-698a33df1c12",
            "sourceColumn": "OnlineOrderFlag",
            "summarizeBy": "none"
          },
          {
            "name": "SalesOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "59eeea54-a12f-4038-b611-0fad104428e1",
            "sourceColumn": "SalesOrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "PurchaseOrderNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5902d7c3-b28a-430a-bc90-de437b6ff5d6",
            "sourceColumn": "PurchaseOrderNumber",
            "summarizeBy": "none"
          },
          {
            "name": "AccountNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "da794800-fe32-4e0a-8892-04f8bd06814f",
            "sourceColumn": "AccountNumber",
            "summarizeBy": "none"
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b8390540-0642-42d0-9c37-c6b525be7e07",
            "sourceColumn": "CustomerID",
            "summarizeBy": "none"
          },
          {
            "name": "ShipToAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f681ec8-1eec-49ac-977f-dafde74445c7",
            "sourceColumn": "ShipToAddressID",
            "summarizeBy": "count"
          },
          {
            "name": "BillToAddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c5aaa6ae-7cbc-46d4-ac7c-c827a4822dd3",
            "sourceColumn": "BillToAddressID",
            "summarizeBy": "count"
          },
          {
            "name": "ShipMethod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "47c407ad-eadf-4960-9040-af978cfe0887",
            "sourceColumn": "ShipMethod",
            "summarizeBy": "none"
          },
          {
            "name": "CreditCardApprovalCode",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8641d33-2c3c-4fd8-a43b-cdebfdf6b803",
            "sourceColumn": "CreditCardApprovalCode",
            "summarizeBy": "none"
          },
          {
            "name": "SubTotal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "3a9eb64f-20d2-4430-9ffe-b65243196b67",
            "sourceColumn": "SubTotal",
            "summarizeBy": "sum"
          },
          {
            "name": "TaxAmt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "9f7f6a3a-d9b3-4f59-af48-4cb494a08eb5",
            "sourceColumn": "TaxAmt",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "4753d279-0195-42b2-b9d4-fd556483ed38",
            "sourceColumn": "Freight",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalDue",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "fbf10374-bff3-4222-a915-d0e7752efe26",
            "sourceColumn": "TotalDue",
            "summarizeBy": "sum"
          },
          {
            "name": "Comment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8090d6b2-82b2-49a8-925a-eaa01e23162d",
            "sourceColumn": "Comment",
            "summarizeBy": "none"
          },
          {
            "name": "rowguid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b005118-3c5a-437a-8e2e-13416514b805",
            "sourceColumn": "rowguid",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e7ad2364-3968-4a19-8ce9-32dd0593c738",
        "partitions": [
          {
            "name": "SalesLT SalesOrderHeader",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"azuresqlserver0517.database.windows.net\", \"sampleDB\"),",
                "    SalesLT_SalesOrderHeader = Source{[Schema=\"SalesLT\",Item=\"SalesOrderHeader\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(SalesLT_SalesOrderHeader,{\"OrderDate\", \"DueDate\", \"ShipDate\", \"ModifiedDate\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "SalesLT CustomerAddress",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e2c86490-11bc-4dc3-b49f-89c7accf1f1d",
            "sourceColumn": "CustomerID",
            "summarizeBy": "count"
          },
          {
            "name": "AddressID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "10cdca5b-39fb-4298-b4a8-0d9d035584ca",
            "sourceColumn": "AddressID",
            "summarizeBy": "count"
          },
          {
            "name": "AddressType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96387721-1c06-4100-91d6-9340d6b9d13d",
            "sourceColumn": "AddressType",
            "summarizeBy": "none"
          },
          {
            "name": "rowguid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c29ef66-ee72-4eaf-996b-d22372fb0109",
            "sourceColumn": "rowguid",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fcb83d7a-dee1-4fb4-9c53-f24db5e4aa79",
        "partitions": [
          {
            "name": "SalesLT CustomerAddress",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"azuresqlserver0517.database.windows.net\", \"sampleDB\"),",
                "    SalesLT_CustomerAddress = Source{[Schema=\"SalesLT\",Item=\"CustomerAddress\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(SalesLT_CustomerAddress,{\"ModifiedDate\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}