{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SalesLT Customer\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "zh-CN",
    "cultures": [
      {
        "name": "zh-CN",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "dbe34cd7-ae86-497a-ae9f-0cdb07e08fa9",
        "fromColumn": "ModifiedDate",
        "fromTable": "SalesLT Customer",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_761f71ca-9511-433f-bce1-2e0c7d2da933"
      }
    ],
    "sourceQueryCulture": "en-GB",
    "tables": [
      {
        "name": "SalesLT Customer",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9577defa-b34d-4c0e-9c42-42f9dd618f64",
            "sourceColumn": "CustomerID",
            "summarizeBy": "count"
          },
          {
            "name": "NameStyle",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "e7be88c2-96e8-43c0-a799-f16853edd646",
            "sourceColumn": "NameStyle",
            "summarizeBy": "none"
          },
          {
            "name": "Title",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0f3b4adb-6ffe-4ee7-b70a-3959246f9735",
            "sourceColumn": "Title",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2a85b6db-5a6e-4d63-9f30-b404c7389bc2",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "MiddleName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3b76758-5481-4a60-b49f-b8470d468420",
            "sourceColumn": "MiddleName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dafac656-8b08-4fab-8da9-4ae70a3eed67",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          },
          {
            "name": "Suffix",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcaf659d-51d6-411c-98cc-06bc686733d6",
            "sourceColumn": "Suffix",
            "summarizeBy": "none"
          },
          {
            "name": "CompanyName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdf0c4c3-a932-4ba6-bd75-9e302adc0763",
            "sourceColumn": "CompanyName",
            "summarizeBy": "none"
          },
          {
            "name": "SalesPerson",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "87ba49cd-2fed-4f71-8aff-ea36909c3ee2",
            "sourceColumn": "SalesPerson",
            "summarizeBy": "none"
          },
          {
            "name": "EmailAddress",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "778458ec-06a0-4ea9-8b80-ac55b4c3cf6c",
            "sourceColumn": "EmailAddress",
            "summarizeBy": "none"
          },
          {
            "name": "Phone",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "60d4971a-ca06-48ce-ba7b-586b9b4f817d",
            "sourceColumn": "Phone",
            "summarizeBy": "none"
          },
          {
            "name": "PasswordSalt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ebf36da-9545-4360-a440-cd7c90e1c0a6",
            "sourceColumn": "PasswordSalt",
            "summarizeBy": "none"
          },
          {
            "name": "rowguid",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7276326b-2e9c-407c-93e3-ac23949e506c",
            "sourceColumn": "rowguid",
            "summarizeBy": "none"
          },
          {
            "name": "ModifiedDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "80a640be-8a03-46ae-ab72-d2ea9af89f06",
            "sourceColumn": "ModifiedDate",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "日期层次结构",
                  "table": "LocalDateTable_761f71ca-9511-433f-bce1-2e0c7d2da933"
                },
                "isDefault": true,
                "relationship": "dbe34cd7-ae86-497a-ae9f-0cdb07e08fa9"
              }
            ]
          }
        ],
        "lineageTag": "3bb2b7bb-6203-40e6-be60-99c9e465e484",
        "partitions": [
          {
            "name": "SalesLT Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Sql.Database(\"azuresqlserver0517.database.windows.net\", \"sampleDB\"),",
                "    SalesLT_Customer = Source{[Schema=\"SalesLT\",Item=\"Customer\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(SalesLT_Customer, each ([CustomerID] = 1 or [CustomerID] = 2 or [CustomerID] = 3 or [CustomerID] = 4 or [CustomerID] = 5)),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"PasswordHash\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_14f117e9-8b5c-42bd-b059-7ae4b9a61034",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6f44f863-fc45-4d68-90cf-8eb58373a53f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1b3db7c8-56db-44a2-93e3-41c6f021be38",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5c9f05e8-caf3-42d9-859c-a470dd0baf4c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "d7191689-e9d0-4eba-acd2-faa1d154bb93",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e0e0d165-357e-487b-93d2-ec00e6ba9617",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "30f4f555-eda4-4c37-9d56-602853a338e7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "47235b57-8445-44dd-a038-c8c6544f1d80",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "565df087-da06-455e-b223-d4e796082a10",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "2b41daee-a6a3-4c1f-8655-502c55c2758a",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "f1baf523-f13a-420c-837c-f90d88267f6b",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "516f5a75-8708-4c94-a699-a6faed9d7edd",
                "ordinal": 3
              }
            ],
            "lineageTag": "cfc06344-174d-4f3a-9328-f893ff71bfe8"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "e686ae32-7ddb-4b2b-a12d-0d158f4be259",
        "partitions": [
          {
            "name": "DateTableTemplate_14f117e9-8b5c-42bd-b059-7ae4b9a61034",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_761f71ca-9511-433f-bce1-2e0c7d2da933",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f2d520b1-436e-4761-9bc1-7ed71f50cbb0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "年",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4a6565df-9874-499e-9e5f-bc8e513ddce9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8037aa60-7fb4-433a-b399-74ae5233bb20",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "月份",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e8ef073e-125e-41d8-b13d-570fff7645d6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c224d86b-8a2e-49a2-aa16-7d22acf57b17",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "季度",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"季度 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "524c4706-ecc7-4214-8c93-c39862ba3698",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "日",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "954891df-da78-427a-9287-20b97158dc0a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "日期层次结构",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "年",
                "column": "年",
                "lineageTag": "c56491db-59d3-4e0f-93e3-a7dce5355f69",
                "ordinal": 0
              },
              {
                "name": "季度",
                "column": "季度",
                "lineageTag": "2f4e5bd5-4b24-4444-8018-eba3adee40ab",
                "ordinal": 1
              },
              {
                "name": "月份",
                "column": "月份",
                "lineageTag": "6b82f71e-dfae-4f0b-accd-a33abe5cbb96",
                "ordinal": 2
              },
              {
                "name": "日",
                "column": "日",
                "lineageTag": "3e4743d1-f5ab-4cce-8f50-c20b666d7e33",
                "ordinal": 3
              }
            ],
            "lineageTag": "b915d97f-b0ea-4526-8038-689b74f7d90c"
          }
        ],
        "isHidden": true,
        "lineageTag": "34537b45-506d-4613-84ad-9fbe15ad1ea9",
        "partitions": [
          {
            "name": "LocalDateTable_761f71ca-9511-433f-bce1-2e0c7d2da933",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('SalesLT Customer'[ModifiedDate])), 1, 1), Date(Year(MAX('SalesLT Customer'[ModifiedDate])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}